version: '3.8'
services:
  backend:
    build: .
    expose:
      - "8000"
    volumes:
      - "log:/home/visualdl/log"
    command: ["--api-only", "--host=0.0.0.0", "--port=8000"]
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8999:8999"
    environment:
      BACKEND: http://backend:8000
      HOST: 0.0.0.0
      PORT: 8999
volumes:
  log:
