export let supportLanguage = ['en', 'cn'];
export let defaultLanguage = supportLanguage[0];

export let langDict = {
  'cn': {
    'runs': '数据流',
    'notRunsSelect': '未选中任何数据',
    'metrics': '度量数据',
    'samples': '样本数据',
    'graphs': '网络结构',
    'HighDimensional': '高维数据映射',
    'text': '文本',
    'image': '图片',
    'audio': '音频',
    'showActualImageSize': '按真实大小显示',
    'startRunning': '运行',
    'stopRunning': '停止',
    'searchTagInReg': '搜索标签(支持正则)',
    'scalars': '标量',
    'smoothing': '平滑度',
    'xAxis': 'x轴',
    'toolTipSorting': '标签排序方法',
    'ignoreOutliers': '图表缩放时忽略极端值',
    'histogram': '直方图',
    'mode': '模式',
    'step': '步',
    'relative': '相对值',
    'wall': '时间',
    'default': '默认',
    'descending': '降序',
    'ascending': '升序',
    'nearest': '最近',
    'overlay': '概览',
    'offset': '偏移',
    'downloadImage': '下载图片',
    'restoreImage': '还原图片',
    'scale': '比例',
    'nodeInfo': '节点信息',
    'nodeName': '节点名称',
    'nodeType': '节点类型',
    'dataShape': '数据形状',
    'dataType': '数据类型',
    'input': '输入',
    'output': '输出',
    'opType': '算子类型',
    'search': '搜索',
    'searchByLabel': '通过标签搜索',
    'dimension': '维度',
    '2D': '二维',
    '3D': '三维',
    'displayAllLabel': '展示所有标签',
    'reductionMethod': '降维方法',
    'downloadDataInJson': '下载数据(json格式)',
    'all': '全部',
  },
  'en': {
    'runs': 'Runs',
    'notRunsSelect': 'None selected',
    'metrics': 'metrics',
    'samples': 'samples',
    'graphs': 'graphs',
    'HighDimensional': 'HighDimensional',
    'text': 'Text',
    'image': 'Image',
    'audio': 'Audio',
    'showActualImageSize': 'Show actual image size',
    'startRunning': 'Running',
    'stopRunning': 'Stopped',
    'searchTagInReg': 'Search tags in RegExp',
    'scalars': 'Scalars',
    'smoothing': 'Smoothing',
    'xAxis': 'X-axis',
    'toolTipSorting': 'Tooltip sorting',
    'ignoreOutliers': 'Ignore outliers in chart scaling',
    'histogram': 'Histogram',
    'mode': 'Mode',
    'step': 'Step',
    'relative': 'Relative',
    'wall': 'Wall Time',
    'default': 'default',
    'descending': 'descending',
    'ascending': 'ascending',
    'nearest': 'nearest',
    'overlay': 'Overlay',
    'offset': 'Offset',
    'downloadImage': 'Download image',
    'restoreImage': 'Restore image',
    'scale': 'Scale',
    'nodeInfo': 'Node Info',
    'nodeName': 'Name',
    'nodeType': 'Node Type',
    'dataShape': 'Shape',
    'dataType': 'Data Type',
    'input': 'Input',
    'output': 'Output',
    'opType': 'Operator Type',
    'search': 'Search',
    'searchByLabel': 'Search by label',
    'dimension': 'Dimension',
    '2D': '2D',
    '3D': '3D',
    'displayAllLabel': 'Display All Labels',
    'reductionMethod': 'Reduction Method',
    'downloadDataInJson': 'Download data in JSON',
    'all': 'All',
  },
};

export function getValueByLanguage(lang, key) {
  if (supportLanguage.indexOf(lang) == -1) {
    lang = defaultLanguage;
  }

  return langDict[lang][key];
}
